<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class brand extends Model
{
    use HasFactory;
    protected $guarded=[];


    public function supplements(){
        return $this->hasMany(product::class,'brand_id','id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($brand){
            \Log::info('new brand with id '.$brand->id.' stored');
        });
    }
}
