<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class category extends Model
{
    use HasFactory;
    protected $guarded=[];

    function subCategories(){
        return $this->hasMany(subCategory::class,'category_id');
    }
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::created(function ($category){
            \Log::info('new category with id '.$category->id.' stored');
        });
    }

}
